package com.example.mesabaseballexhibit.features;

import com.example.mesabaseballexhibit.R;
import java.util.ArrayList;
import java.util.List;

public class InducteeData {
    public static List<com.example.mesabaseballexhibit.features.Inductee> getInducteesForYear(int year) {
        List<com.example.mesabaseballexhibit.features.Inductee> list = new ArrayList<>();
        if (year == 2014) {
            list.add(new com.example.mesabaseballexhibit.features.Inductee(R.drawable.dwight_patterson,
                    "Dwight 'Pat' Patterson",
                    "Mesa Rancher and Businessman",
                    "One of the Cactus League's biggest civic boosters, he is credited with bringing the Chicago Cubs to Mesa in 1952 and then bringing them back to Mesa from Scottsdale in 1979. He was the first chairman of the storied Hohokams civic club, created to pursue a spring training baseball team in 1946 and was selected by Governor Rose Mofford to lead her task force to save spring training in the late 1980's."));
            list.add(new com.example.mesabaseballexhibit.features.Inductee(R.drawable.horace_stoneham,
                    "Horace Stoneham",
                    "Owner, New York/San Francisco Giants, 1936 - 1976",
                    "Horace Stoneham is credited with helping to start the Cactus League when he moved his team to Phoenix from Florida in 1947. Himself the owner of a winter home in Phoenix at the time, Stoneham also swapped\n" +
                    "spring camps with Del Webb in 1951, when Mr. Webb proposed bringing his New York Yankees to the Cactus League for a season of baseball and selling homes. Stoneham's team spent more than two dec-\n" +
                    "ades visiting the Buckhorn Baths and Mineral Springs in Mesa leaving a rich trail of spring training historyand memories that continue to amaze fans today."));
            list.add(new com.example.mesabaseballexhibit.features.Inductee(R.drawable.bill_veeck_jr,
                    "Bill Veeck, Jr., 1946 - 1949",
                    "Owner, Cleveland Indians",
                    "Bill Veeck, Jr. is credited with helping to start the Cactus League when he moved his team to Tucson from Florida in 1947. Urged by Arizona State Senator Hiram Corbett of Tucson, Veeck wanted to move his newly acquired team to be near his Southern Arizona guest ranch. He was able to accomplish his goal when he found another owner willing to join him in the desert, N.Y. Giants owner Horace Stoneham."));
            list.add(new com.example.mesabaseballexhibit.features.Inductee(R.drawable.hon_rose_mofford,
                    "Hon. Rose Mofford",
                    "Arizona Governor, 1988 - 1991",
                    "Former Arizona Governor Rose Mofford was in the right place at the right time when it came to the task of saving spring training baseball in Arizona. Florida interests were known to have contacted every team that trained in Arizona at the time, but it was the threat of losing the Chicago Cubs and Cleveland Indians that caused the most concern. In 1988, Governor Mofford, herself a former All-American softball player with the Cantaloupe Queens, appointed a task force to study ways to keep teams training in Arizona. The task force's work led to retention of the teams already here, the addition of new teams and an explosion in fan attendance. Governor Mofford saved spring training and cemented the Cactus League as a fixture in the state."));
            list.add(new com.example.mesabaseballexhibit.features.Inductee(R.drawable.ted_and_alice_sliger,
                    "Ted and Alice Sliger",
                    "Owners of the Buckhorn Baths, Mesa, AZ, 1935 - 2010",
                    "When their gas station burned down in 1935, the couple purchased ten acres of land at the northwest corner of Apache Trail and Recker Road then located miles east of Mesa. While digging a well, they discovered a mineral spring that spurred the development of a series of small bathhouses, complete with a Roman style bath and cooling room. The resort quickly became a favorite pre-Spring Training ritual for select members of the New York and San Francisco Giants and other baseball celebrities over the years."));
            list.add(new com.example.mesabaseballexhibit.features.Inductee(R.drawable.hiram_corbett,
                    "Hiram “Hi” Corbett",
                    "Arizona State Senator, Tucson, AZ, 1953 - 1964",
                    "Hi Corbett was a Tucson native who is credited with helping to convince Bill Veeck to bring his Cleveland Indians to Southern Arizona for spring training, giving rise to the Cactus League. Corbett was an amateur golfer who organized Tucson's first professional golf tournament, was President of the Texas Baseball eague, and served his community in the Arizona State Senate. The ballpark that played host to the Indi ans (and ultimately the expansion of the Colorado Rockies) was named after him in 1951."));
            }
        if (year == 2016) {
            list.add(new com.example.mesabaseballexhibit.features.Inductee(R.drawable.dwight_patterson,
                    "Dell Webb",
                    "Co-Owner, New York Yankees 1947-1964",
            "Del Webb is one of the most prominent names in Cactus League history. A lifelong fan of baseball, Webb parlayed his success as the president of the Phoenix-based Del Webb Construction Co. into co-ownership of the Yankees. Del Webb is credited with one of the most interesting trades in base ball history. In 1951, Webb convinced New York Giants owner Horace Stoneham to swap spring training sites for a single year, sending the Giants to Florida and the Yankees to the original Phoenix Municipal Stadium. The Yankees’ were the defending World Champions that year, with a lineup that included Joe Dimaggio in his last season, Mickey Mantle and Yogi Berra, under the management of manager Casey Stengel. Not only was Webb able to showcase the Yankees to other Arizona brass as he was building Sun City—he gave fans a close-up look of a national market team years before Major League Baseball’s westward expansion."));
            list.add(new com.example.mesabaseballexhibit.features.Inductee(R.drawable.dwight_patterson,
                    "Gene Autry",
                    "Owner, Los Angeles Angels 1961-1988",
            "Autry was one of the most recognizable owners in baseball history, and a major contributor to the success of spring training in Arizona. Though his Angels first trained in Palm Springs, Autry eventually moved the team to Tempe Diablo Stadium in 1993. He would go on to lead later expansion efforts for the Tempe Diablo complex. Known as the Singing Cowboy in the 1930s, Gene Autry moved on to broadcasting before baseball came calling. In 1960, while looking to secure broadcasting rights to a new California expansion team, he was instead persuaded to become the team’s owner—and the Los Angeles Angels were born. After he died, the Angels retired the number 26 in his honor, reflectingm his position as the unofficial 26th member of the team’s 25-member roster. And in 1999, the Angels renamed the stadium Tempe Diablo Gene Autry Field, and his famous ballad “Back in the Saddle continues to be played after each game."));
            list.add(new com.example.mesabaseballexhibit.features.Inductee(R.drawable.dwight_patterson,
                    "Robert Brinton",
                    "Mesa HohoKams President 2009-2010, Cactus League Board Member and President, 1989-2011",
            "Robert Brinton had a close connection to the Cactus League and left an impression on everyone who knew his efforts to support and expand it. Robert Brinton’s love of baseball started early. His father, Dilworth Brinton, worked with Mesa rancher Dwight Patterson to help lure the Chicago Cubs to Mesa, helping to preserve Major League Baseball’s presence in Arizona, tirelessly promoting the importance cal efforts helped prevent the migration of teams to Florida, as did his leadership on the 2012 Keep_the Cubs bond election in Mesa."));
            list.add(new com.example.mesabaseballexhibit.features.Inductee(R.drawable.dwight_patterson,
                    "Jim Bruner",
                    "Charro of the Year 1976-1977, Baseball Chairman 1980,\n" +
                            "Hallstrom Lifer of the Year 2004-2005 and 2007-2008",
                    "A mover and shaker in every sense of those words, Jim Bruner has certainly achieved legendary status in Arizona’s baseball history. Pursuing his interest in bringing a Major League Baseball franchise to Arizona, Bruner worked his influence as a member of both the Scottsdale City Council and the Maricopa County Board of Supervisors to persuade sports mogul Jerry Colangelo to form an ownership group. And, it was Bruner’s deciding vote that implemented the funding mechanism for a county-owned stadium, home of the Arizona Diamondbacks. Bruner served for three and a half years ashen-governor Rose Mofford to stabilize and expand the Arizona Cactus League in the late 1980s when Florida was threatening to lure Cactus League teams to the Grapefruit League. Thanks to him fifteen MLB teams and their fans come to Arizona every spring to begin another exciting season."));
        }
        if (year == 2017) {
            list.add(new com.example.mesabaseballexhibit.features.Inductee(R.drawable.dwight_patterson,
                    "Ernie Banks",
                    "Mesa Rancher and Businessman",
                    "One of the Cactus League's biggest civic boosters, he is credited with bringing the Chicago Cubs to Mesa in 1952 and then bringing them back to Mesa from Scottsdale in 1979. He was the first chairman of the storied Hohokams civic club, created to pursue a spring training baseball team in 1946 and was selected by Governor Rose Mofford to lead her task force to save spring training in the late 1980's."));
            list.add(new com.example.mesabaseballexhibit.features.Inductee(R.drawable.dwight_patterson,
                    "Monte Irvin",
                    "Outfielder, New York Giants, 1949–1955",
                    "Signed by the New York Giants, outfielder Monte Irvin was among the first four players to integrate spring training baseball in Arizona, making his major league debut in July of 1949. By the time Monte signed with the Giants he was already a bona fide four-time all-star in the Negro Leagues and two-time Negro National League batting champion. Irvin played for the New York Giants from 1949-1955 and spent five spring training seasons with the team in Phoenix. He also spent one spring season at Mesa’s Rendezvous Park with the Chicago Cubs in 1956. Irvin enjoyed his best season with the Giants in 1951 hitting .312 with 24 home runs and a National League leading 121 RBI. Monte played for two NL pennant-winning clubs (1951 and 1954) and one World Series champion (1954). Irvin became Major League Baseball’s first African-American executive when hired to the commissioner’s office in 1968. He was elected to the National Baseball Hall of Fame in 1973 by the Special Committee on Negro Leagues."));
            list.add(new com.example.mesabaseballexhibit.features.Inductee(R.drawable.dwight_patterson,
                    "Larry Doby",
                    "Center Fielder, Cleveland Indians, 1947–1955",
                    "Larry Doby was already a star baseball player with the Negro League Newark Eagles and had served a stint in the U.S. Navy during World War II when Bill Veeck signed him to play for the Cleveland Indians in July of 1947. Doby was the first Negro League player to go directly to the Major Leagues and the first African-American player in the American League, debuting 81 days after Jackie Robinson broke baseball’s color barrier. In the spring of 1948 Larry became the first African-American to play in Arizona’s Cactus League. Playing centerfield in the 1948 World Series Doby hit .318 and belted the deciding home run in Game 4, helping the Indians take the title in six games. He was a seven-time All-Star, leading the American League in home runs twice, finishing his 12-year Big League career with 253 home runs. Larry Doby was elected to the National Baseball Hall of Fame in 1998."));
            list.add(new com.example.mesabaseballexhibit.features.Inductee(R.drawable.dwight_patterson,
                    "Willie Mays",
                    "Center Fielder, New York Giants, 1951–1957",
                    "The greatest Giant of them all Willie Mays, will always be considered among baseball’s best all-around players. “The Say Hey Kid” was a five-tool player before the term existed excelling in all aspects of the game, Mays could hit for average and power, run, throw and play defense as well if not better than any of his contemporaries and few before or since. Mays won the National League’s first Gold Glove Award in 1957 and a record tying 12 consecutive in the ensuing years to follow. Mays was just the fourth African-American player signed by the New York Giants, the 17th in major league history, and was among the pioneering players to integrate spring training baseball in Arizona joining the Giants in Phoenix prior to his first full season in 1952. The first major-league player to hit 50 home runs and steal 20 bases in the same season, Mays was also the first member of the National League’s 30/30 club (30 HRs and 30 steals in the same season) a feat that he accomplished in back-to-back seasons in 1956 and 1957. At the time of his retirement Mays ranked third in home runs (660), runs scored (2,062) and total bases (6,066) and was among the top 10 in hits (3,283), RBI (1,903) and first in putouts by an outfielder (7,095). He won the National League Rookie of the Year Award in 1951 and the league MVP award in 1954 and 1965."));
        }
        if (year == 2018) {
            list.add(new com.example.mesabaseballexhibit.features.Inductee(R.drawable.dwight_patterson,
                    "Frank Robinson",
                    "Mesa Rancher and Businessman",
                    "One of the Cactus League's biggest civic boosters, he is credited with bringing the Chicago Cubs to Mesa in 1952 and then bringing them back to Mesa from Scottsdale in 1979. He was the first chairman of the storied Hohokams civic club, created to pursue a spring training baseball team in 1946 and was selected by Governor Rose Mofford to lead her task force to save spring training in the late 1980's."));
            list.add(new com.example.mesabaseballexhibit.features.Inductee(R.drawable.dwight_patterson,
                    "Dwight 'Pat' Patterson",
                    "Outfielder/Designated Hitter, Cincinnati Reds, 1956–1965",
                    "Frank Robinson made his debut with the Cincinnati Reds in 1956 capturing the NL Rookie of the year award hitting a then rookie record 38 home runs. He is the first (and only) player to win the MVP award in both Leagues; with the Reds in 1961 and the Baltimore Orioles in 1966 when he also captured the AL Triple Crown leading the league with 49 HRs, 122 RBI and a .316 batting average. Towards the end of his 21-year Hall of Fame career Robinson became Major League Baseball’s first African American manager while doubling as a designated hitter for the Cleveland Indians in 1975. Robinson managed his former Orioles team from 1988-1991 and was named American League Manager of the Year in 1989. Robinson was presented with the Presidential Medal of Freedom in 2005 and received MLB’s Beacon of Life Award in 2008 for embodying the spirit of the civil rights movement. He was elected to the National Baseball Hall of Fame in 1982. "));
            list.add(new com.example.mesabaseballexhibit.features.Inductee(R.drawable.dwight_patterson,
                    "Bob Uecker",
                    "Catcher, Milwaukee Braves, 1962–1963",
                    "Bob Uecker grew up in Wisconsin and signed with the hometown Milwaukee Braves, making his six-year Major League career debut as a catcher in 1962. It was after his playing days when his career took off as an actor, comedian, author, and broadcaster. Known as “Mr. Baseball”, Uecker has been behind the microphone for the Brewers since 1971. He’s also announced Championship and World Series games and was honored by the National Baseball Hall of Fame with its 2003 Ford C. Frick Award for his broadcasting. Uecker’s far ranging career has included: Hosting his own syndicated TV shows, appearing on Johnny Carson’s Tonight Show, guest hosting Saturday Night Live, WWE Hall of Fame inductee as a wrestling announcer, spokesperson for Miller Lite, authoring the book - Catcher in the Wry and acting as a radio announcer in the Major League film trilogy. "));
            list.add(new com.example.mesabaseballexhibit.features.Inductee(R.drawable.dwight_patterson,
                    "Gaylord Perry",
                    "Pitcher, San Francisco Giants, 1962–1971",
                    "North Carolina native Gaylord Perry pitched for eight teams in his 22 year Major League career. His longest stint (10 years) was with his original club, the San Francisco Giants. Debuting in 1962, he had his first 20-win campaign and All-Star Game appearance in 1966. The Giants traded Perry in 1971 to the Indians where he thrived. His 24-win, 1.92 ERA for Cleveland in 1972 won him the A.L. Cy Young Award, an honor he repeated in 1978 for the San Diego Padres -- at age 39. Perry was the first pitcher to win a Cy Young in both leagues. In 1982 he won his 300th game with the Mariners. At the time of his retirement Perry's total of 314 wins ranked 10th all-time and his 3,534 strikeouts were third. He spent 17 of his 22 springs in he Cactus League. Gaylord Perry was elected to the National Baseball Hall of Fame in 1991. "));
            list.add(new com.example.mesabaseballexhibit.features.Inductee(R.drawable.dwight_patterson,
                    "Yosh Kawano",
                    "Clubhouse Manager, Chicago Cubs, 1953–2008",
                    "Chicago Cubs Clubhouse Manager Yosh Kawano retired in 2008 after an amazing 65 year run with the team. Kawano, a Japanese American, and his family were held at Poston War Relocation Center in Arizona during World War II. While interned, Kawano wrote a letter to Chicago White Sox manager Jimmy Dykes, who had befriended Yosh during his spring training stint as bat boy. With the assistance of Dykes’ intervention on his behalf, Kawano was released from the internment camp and traveled to Chicago where he was hired by the Cubs as a clubhouse assistant. Kawano continued in his role as clubhouse assistant until he was appointed clubhouse manager in 1953 after the retirement of long-time trainer Andy Lotshaw. He was so beloved that when the Wrigley family sold the Cubs to the Tribune Company in 1981, the contract stipulated Kawano would always have a job with the team. He donated his trademark white fishing cap to the National Baseball Hall of Fame in Cooperstown, New York."));
            list.add(new com.example.mesabaseballexhibit.features.Inductee(R.drawable.dwight_patterson,
                    "Derrick Moore",
                    "Concessions Vendor, Cactus League, mid-1980s–Present",
                    "“Lemonade, Lemonade Like Grandma Made!” With his signature call , vendor Derrick Moore has entertained Cactus League baseball fans for decades as one of the most widely recognized ballpark personalities in the league’s history. Moore has been a familiar and friendly presence on Arizona’s sporting scene since the mid-1980s when he began selling soda at Scottsdale Stadium. He’s hawked concessions at almost every Cactus League ballpark in operation during his career. In 2015 Derrick Moore was named #TopMLBVendor in an online poll of Major League Baseball fans."));

        }
        if (year == 2019) {
            list.add(new com.example.mesabaseballexhibit.features.Inductee(R.drawable.dwight_patterson,
                    "Ken Griffey, Jr.",
                    "Center Fielder, Seattle Mariners, 1989–1999",
                    "Ken Griffey Jr., known as “Junior” and “The Kid,” became “The One” to watch during Cactus League action. Bursting onto the Major League scene at age 19, Griffey Jr.’s bat and glove catapulted him to a career that was a throwback to an era of players who could do it all – hit, run and field. He spent 14 of his 22-year Major League career in the Cactus League. From 1989-1999 he played with the Mariners, in 2008 with the Chicago White Sox and 2009-2010 again with the Mariners. A 13-time All-Star, Griffey Jr. was one of the most prolific Home Run hitters in baseball history. He won 10 straight Gold Gloves, 7 Silver Slugger awards, and the American League’s MVP in 1997. When he was inducted into the National Baseball Hall of Fame in Cooperstown in 2016, his first year of eligibility, he received the highest percentage of votes in the Hall’s history – 99.32 percent."));
            list.add(new com.example.mesabaseballexhibit.features.Inductee(R.drawable.dwight_patterson,
                    "Bobby Freeman",
                    "Official Organist, Arizona Diamondbacks, 1998–Present",
                    "The keeper of one of baseball’s grand traditions, Bobby Freeman has provided the soundtrack to baseball in Arizona since making his professional debut with the San Francisco Giants AAA Pacific Coast League affiliate, Phoenix Firebirds at Phoenix Municipal Stadium in 1989. Freeman ushered in the inaugural Arizona Fall League season in 1993 and began his long-standing Cactus League affiliation with the San Diego Padres and Seattle Mariners at the new Peoria Stadium in 1994. The Official Organist of the Arizona Diamondbacks since the inaugural season of 1998, Freeman also played at the team’s Tucson Electric Park spring training site during the team’s 13 Cactus League seasons and played for the grand openings of the Chicago Cubs new HoHoKam Park in Mesa, the Milwaukee Brewers Maryvale Baseball Park, and the Cleveland Indians/Cincinnati Reds Goodyear Ballpark. Freeman has preserved the art of the ballpark organist for more than a generation and has been the Official Organist for the Arizona Diamondbacks at the team’s Salt River Fields ballpark since its opening in 2011."));
            list.add(new com.example.mesabaseballexhibit.features.Inductee(R.drawable.dwight_patterson,
                    "Ferguson “Fergie” Jenkins",
                    "Pitcher, Chicago Cubs, 1966–1973",
                    "One of Major League Baseball’s greatest and most dominant pitchers of all-time, On a roster filled with diversity and a drive to win, Ferguson “Fergie” Jenkins was a key member of the Chicago Cubs from 1966 -1973. Fine-tuning his pitching trade in Arizona’s Cactus League, the 1971 Cy Young Award winner and three-time All-Star, attributed a big part of his successful career to training in Arizona’s warm temperatures. During his 19-year Major League career, Jenkins spent 10 of them in the Cactus League: 1967 to 1973 at the original Scottsdale Stadium, and 1982 to 1983 at the then-new Hohokam Stadium in Mesa. His 284 career wins, 3,192 strikeouts, 3.34 Earned Run Average, and 267 complete games out of 664 appearances are just part of his legacy. In retirement, Jenkins continues to go the distance as a strong presence and great ambassador for baseball during Cactus League seasons."));
            list.add(new com.example.mesabaseballexhibit.features.Inductee(R.drawable.dwight_patterson,
                    "Roland Hemond",
                    "General Manager, Chicago White Sox, 1970–1985",
                    "Major League executive Roland Hemond is revered for his kindness and generosity of spirit as much as his baseball acumen. He has served as a mentor to multiple generations of future baseball executives. Hemond was the first recipient of the National Baseball Hall of Fame’s Buck O’Neil Award in 2011. This is an award presented to individuals whose extraordinary efforts enhanced baseball’s positive impact on society and broadened the game’s appeal. Hemond’s 70 year career includes working as general manager for the Chicago White Sox (1970 -1985) and the Baltimore Orioles (1988 – 1995). He also worked in executive offices for five different teams. Roland Hemond’s further accomplishments include earning World Series rings with Milwaukee in 1957, the Diamondbacks in 2001 and the White Sox in 2005. A constant presence in the Cactus League, Roland has also been credited with creating the Arizona Fall League."));
            list.add(new com.example.mesabaseballexhibit.features.Inductee(R.drawable.dwight_patterson,
                    "Robin Yount",
                    "Shortstop/Center Fielder, Milwaukee Brewers, 1974–1993",
                    "Teenage phenom Robin Yount made his big league debut with the Milwaukee Brewers at the age of 18 on Opening Day in 1974 and never wore another team’s uniform for the duration of his 20-year career. He is the franchise leader in at-bats, hits, singles, doubles, triples, walks, RBI and total bases. Nicknamed “The Kid”, Yount played the game with a boyish enthusiasm, but immediately proved himself a peer among men anchoring the shortstop position for 11 years before moving to the outfield for the second half of his career. He is one of only four players to win his league’s MVP award at two positions; at shortstop for the Brewer’s American League champion team in 1982, and center field in 1989. A three-time All-Star and Silver Slugger Award winner, Yount received the Gold Glove Award at shortstop in 1982. The last major leaguer to have been a teammate of Hank Aaron, Yount spent all 20 of his spring training seasons with the Brewers in Arizona. His number 19 was retired by the Milwaukee franchise one year after he announced his retirement in 1993 and he was elected to the National Baseball Hall of Fame in his first year of eligibility in 1999."));
        }
        if (year == 2020) {
            list.add(new com.example.mesabaseballexhibit.features.Inductee(R.drawable.dwight_patterson,
                    "Allan H. \"Bud\" Selig",
                    "Baseball Executive and MLB Commissioner",
                    "Born July 30, 1934, in Milwaukee, Wisconsin, Allan H. \"Bud\" Selig grew up a baseball fan, rooting for the then-minor league Milwaukee Brewers and later the Milwaukee Braves when they moved to Wisconsin in 1953. When the Braves moved to Atlanta for the 1966 season, Selig set out to work on bringing MLB back to his hometown. His efforts came to fruition on March 31, 1970, when Selig led a group that purchased the Seattle Pilots out of bankruptcy court. Seven days later, the Milwaukee Brewers opened their first MLB season. A consensus builder, Selig soon became one of baseball's most influential owners. On July 9, 1998, Selig was formally appointed commissioner. His 16-year tenure was second only to Kenesaw Mountain Landis' 24 years in the office. One of Selig's most notable achievements came in 1997, when he announced that the uniform number 42 would be retired across baseball to honor Jackie Robinson."));
            list.add(new com.example.mesabaseballexhibit.features.Inductee(R.drawable.dwight_patterson,
                    "Alan \"Al\" Siebert ",
                    "Peoria Sports Facilities Superintendent",
                    "Al Siebert was a fixture of spring training in Peoria during a 30-year career that ended in his retirement in 2019. Hired by the City of Peoria in 1989, Siebert served on the ground crew that opened Peoria Sports Complex in 1994 as the spring training home of the Seattle Mariners and San Diego Padres. It became the first shared spring training facility in either Arizona or Florida and established the model that assured the future of the Cactus League. Siebert was appointed Peoria Sports Complex Supervisor in 2008 and spent the last four years as the city's Sports Facilities Superintendent. In 2018, Siebert's work was recognized by the Sports Turf Managers Association, which awarded Peoria Sports Complex with the organization's Environmental Facility Certification, bestowed on sports facilities that showcase ecologically friendly and sustainable best practices."));
            list.add(new com.example.mesabaseballexhibit.features.Inductee(R.drawable.dwight_patterson,
                    "Tony Gwynn",
                    "Hall of Fame Right Fielder",
                    "Born May 9, 1960 in Los Angeles, Anthony Keith Gwynn Sr. became one of baseball's greatest hitters. Known as \"Mr. Padre,\" Gwynn played his entire 20-year MLB career with the San Diego Padres from 1982-2001. The left handed-hitting outfielder won eight National League batting titles, tied for the most in league history. Consistent greatness was Gwynn's trademark at the plate: he had a .338 lifetime batting average and never hit below .309 in any full season. He also excelled in the field, earning five Gold Gloves. Gwynn was a popular Cactus League fixture, patiently signing autographs and posing for photos with fans. Plagued by knee injuries late in his career, Gwynn retired after the 2001 season with 3,141 career hits. The Padres retired Gwynn's number 19 in 2004. Gwynn was inducted into the Baseball Hall of Fame in 2007, his first year of eligibility."));
            list.add(new com.example.mesabaseballexhibit.features.Inductee(R.drawable.dwight_patterson,
                    "Billy Williams",
                    "Hall of Fame Left Fielder",
                    "Billy Leo Williams was born June 15, 1938 in Whistler, Alabama and grew up in a segregated neighborhood. He began playing professional baseball in 1956 with the Ponca City Cubs of the Sooner State League. Williams was the 1961 National League Rookie of the Year. For 16 seasons, Williams anchored left field for the Cubs, becoming as much a part of Wrigley Field as the ivy-covered outfield walls. In each season, from 1961-1973, the sweet-swinging Williams hit at least 20 home runs and drove in 84 runs. Williams was a six-time All-Star and won the 1972 NL batting title. Williams was traded to Oakland after the 1974 season and helped the A's win the 1975 American League West championship. In 1987, Williams was elected to the Baseball Hall of Fame, and his Cubs' uniform number 26 was retired. In 1999, he was selected to the Cubs All-Century team, and in 2010 Williams was honored with the unveiling of his statue outside Wrigley Field."));
            list.add(new com.example.mesabaseballexhibit.features.Inductee(R.drawable.dwight_patterson,
                    "Vida Blue MVP and Cy Young",
                    "Award-Winning Pitcher",
                    "Vida Rochelle Blue, Jr., was born July 28, 1949 in Mansfield, Louisiana. At Mansfield's De Soto High School, he threw a 7-inning no-hitter, recording every out by strikeout. In 1969, Blue signed a contract with the Oakland A's, and he soon became one of baseball's most-feared left-handed pitchers. In 1971, Blue achieved a rare double honor, winning the American League Cy Young Award and Most Valuable Player. Blue played a pivotal role in the Oakland A's three consecutive World Series Championships from 1972 to 1974. Blue was a six-time All-Star and the first pitcher to start an All-Star Game for both the American and National Leagues. On Sept. 21, 1970, Blue fired a no-hitter against the Minnesota Twins in his 16th career game. Blue went 209-161 with a 3.27 ERA in 17 Major League season, pitching for Oakland, San Francisco and Kansas City. He is a member of the Athletics Hall of Fame and the Giants Wall of Fame."));
            list.add(new com.example.mesabaseballexhibit.features.Inductee(R.drawable.dwight_patterson,
                    "Vin Scully",
                    "Legendary Dodgers Sportscaster",
                    "Vincent Edward Scully was born in the Bronx, N.Y., on Nov. 29, 1927. Scully fell in love his baseball at age 8, when he followed the New York Giants in the 1936 World Series. After serving in the U.S. Navy for two years and working as a student broadcaster and journalist at Fordham University, Scully joined the Dodgers' broadcast team in 1950- a position he would hold in Brooklyn and Los Angeles for 67 years, until his retirement in 2016 at age 88. At the time he retired, Scully had called Dodger games for more than half of their 133-year history. A Los Angeles icon, Scully had many connections to Hollywood. The creator of the X-Files, a big Dodger fan, named agent Dana Scully in homage to the Dodger broadcaster. "));

        }
        return list;
    }
}
